name: Format, test and push if needed

on:
  push: {}

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Test formatting
        run: |
          results="$(gofmt -s -l .)"

          if [[ -n "${results}" ]]; then
            echo "The following files are not formatted:"
            echo "${results}"
            exit 1
          fi

  test:
    name: Run tests
    runs-on: ${{ matrix.platform }}
    needs:
      - check-formatting

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Verify builds
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

  push:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - check-formatting
      - test

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: pidpawel/scep:latest
